Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 1152
      Handler: com.kenzie.marketing.referral.service.lambda.DeleteReferrals
      CodeUri: C:\Users\bldoo\kenzie\Term4\u5p-brookelynndoonan\ReferralServiceLambda
      Runtime: java11
      Architectures:
        - x86_64